baseURL = "https://deepthought.blog/"
languageCode = "en-us"
title = "Deep Thought"
theme = "hugo-theme-tufte-css"
googleAnalytics = "UA-124170616-1"

[params]
description = "Deep Thought aims at helping you become a better software developer by bringing you distilled, time-tested ideas about the craft of writing code."

[permalinks]
  article = "/:year/:month/:title/"
